export const en = {
  common: {
    back: "back",
    continue: "continue",
    loading: "…",
  },
  player: {
    mute: "mute",
    unmute: "unmute",
    solo: "solo",
  },
  range: {
    low: "low",
    high: "high",
    now: "now",
  },
  language: {
    eyebrow: "welcome",
    titleA: "Pick your",
    titleB: "language.",
    subtitle: "UI stays English. AI feedback comes in this language.",
    continue: "continue",
    options: ["English", "Russian", "Spanish", "German", "French", "Chinese"] as const,
  },
  library: {
    eyebrow: "Library",
    titleA: "Your",
    titleB: "songs.",
    urlPlaceholder: "youtube.com/watch?v=...",
    paste: "PASTE",
    audioFile: "audio · video",
    process: "process",
    queueing: "queueing…",
    allChip: "all",
    inProgressChip: "in progress",
    inProgressSection: "— in progress",
    readySection: "— ready",
    empty: "Library is empty.",
    bringSong: "bring a song",
    streakDay: "day",
    streakDays: "days",
    streakLabel: "warm-up streak",
    warmFirst: "warm up your voice first — 8 min",
    statusProcessing: "processing",
    statusFailed: "failed",
    statusUntitled: "untitled",
    delete: "delete",
  },
  karaoke: {
    eyebrow: "karaoke",
    titleA: "With vocals",
    titleB: "or without.",
    loading: "loading…",
    error: "error",
    clickToPlay: "tap to play",
    backToPlay: "exit",
    showVideo: "video",
    hideVideo: "no video",
    stems: "stems",
    transport: "transport",
    tempo: "tempo · pitch",
    music: "music",
    splitMusic: "+ split music",
    hideSplit: "− hide split",
    nowStudying: "now studying",
    compactPlayer: "compact player",
    toggleVideoTitle: "toggle video background",
    hideControls: "hide controls",
    showControls: "show controls",
    ariaSeek: "seek",
    ariaPlayPause: "play/pause",
    ariaBack15: "back 15s",
    ariaForward15: "forward 15s",
    ariaMuteVocals: "mute vocals",
    ariaUnmuteVocals: "unmute vocals",
    drillAB: "drill A–B",
  },
  play: {
    eyebrow: "now playing",
    titleA: "Sing",
    titleB: "along.",
    loading: "loading stems…",
    stems: {
      vocals: "vocals",
      instrum: "instrum.",
      drums: "drums",
      bass: "bass",
      guitar: "guitar",
      piano: "piano",
      other: "other",
    },
    showExtras: "+ drums / bass",
    hideExtras: "− hide extras",
    learnHint: "learn",
    karaokeHint: "karaoke",
    ariaPlayPause: "play/pause",
    ariaBack15: "back 15s",
    ariaForward15: "forward 15s",
    ariaSeek: "seek",
  },
  processing: {
    eyebrow: "processing",
    titleA: "Stems are",
    titleB: "rising.",
    titleFallback: "Untitled",
    stageEyebrow: "stages",
    leaveHint: "feel free to leave — we'll be here when you're back",
    errorPrefix: "error",
    stages: {
      resolve_input: "Downloading audio",
      separate: "Stem separation",
      asr: "ASR · word-level timing",
      lrclib: "LRCLib lookup",
      align: "Alignment",
    },
    phases: {
      separate: [
        "splitting channels",
        "isolating vocals",
        "extracting drums",
        "lifting bass",
        "pulling guitar · piano",
        "finishing up",
      ],
    },
  },
  drill: {
    eyebrow: "drill",
    titleA: "Loop",
    titleB: "it.",
    emptyPhrase: "no phrase to drill — track has no aligned lyrics",
    prevChunk: "previous chunk",
    nextChunk: "next chunk",
    chunk: "chunk",
    line: "Line",
    custom: "Custom",
    pre: "pre",
    post: "post",
    tempo: "tempo",
    key: "key",
    acappella: "a cappella",
    withVocals: "with vocals",
    minus: "minus",
    restartLoop: "restart loop from A",
    loops: "loops",
    mastered: "mastered",
    gotIt: "got it",
    masteryNeedChunk: "save as chunk first to track mastery",
    masteryUnmark: "unmark mastered",
    masteryMark: "mark mastered & next",
    processing: "…",
  },
  select: {
    eyebrow: "pick a phrase",
    titleA: "What to",
    titleB: "learn.",
    hint: "tap & drag across words to pick a phrase to drill",
    word: "word",
    words: "words",
    clear: "clear",
    drill: "drill",
    saveChunk: "save chunk",
    myChunks: "my chunks",
    stop: "stop",
    playAll: "play all",
    previewTitle: "preview",
    drillArrow: "drill →",
    loadStemsHint: "tap ▶ to load stems for preview",
    mastered: "✓ mastered",
    best: "best",
    close: "close",
  },
  warmup: {
    eyebrow: "warm-up",
    titleA: "Wake the",
    titleB: "voice.",
    rangeTuned: "tuned to",
    rangeFirst: "first, find your range",
    todaysSession: "today's session",
    dailyTitle: "Daily 8",
    dailyMeta: "8 min · before practice",
    streakNone: "ready to start",
    streakDay: "day",
    streakSuffix: "streak",
    startDaily: "start Daily 8",
    letsBegin: "let's begin",
    setupRange: "Set up your range — 60s",
    setupHint: "we tune every exercise to your voice",
    startOnboarding: "start onboarding",
    scienceNote: "5–8 minutes is enough. The act of warming up matters more than the perfect method.",
    stepLabels: ["release", "lip-trill", "siren", "scale", "swell", "staccato", "cool"],
  },
  warmupOnboarding: {
    findingRange: "finding your range",
    scanA: "Slide your",
    scanB: "voice.",
    hintScan: "from your lowest comfortable note up to your highest\nhold each end for a second so it locks",
    locked: "locked",
    listening: "listening",
    detected: "detected",
    tapMicToStart: "tap mic to start",
    chestVoiceTip: "Sing in your chest voice — your normal speaking tone. No falsetto, no straining. Comfort wins.",
    micDenied: "microphone access denied",
    startRecording: "start recording",
    stopRecording: "stop recording",
    hintWhenRecording: "pause for a moment when you're done — it'll save itself",
    hintWhenIdle: "tap mic, slide from low to high, then pause",
  },
  warmupSession: {
    close: "close",
    of: "of",
    prev: "prev",
    next: "next",
    pause: "pause",
    play: "play",
    skipHint: "— too much? tap “next” to skip",
    breathe: "breathe · 4s in · 4s out",
    breatheShort: "breathe",
    holdOn: "hold on",
    steady: "steady",
    softLoudSoft: "soft → loud → soft",
    humSettle: "hum · let it settle",
    gentle: "gentle",
    lip: "lip",
    trill: "trill",
    straw: "straw",
  },
  warmupSteps: {
    release: {
      eyebrow: "— body release —",
      title: 'Open the <em>jaw.</em>',
      meta: "yawn-sigh · shake it loose",
      tip: "Drop the jaw, let the sigh out. No singing yet.",
    },
    sovt: {
      eyebrow: "— sovt primer —",
      title: 'Lip trills <em>or</em> straw.',
      meta: 'pick one · gentle "brrr" or sing through a straw',
      tip: "Half-closed tract = back-pressure. Safest way to wake the cords.",
    },
    siren: {
      eyebrow: "— sirens —",
      title: 'Slide <em>low</em> to high.',
      meta: 'on "ng" · low → high → low, smooth',
      tip: "Don't push at the top. If it strains, lower the target — comfort wins.",
    },
    scale: {
      eyebrow: "— vowel scales —",
      title: 'Climb the <em>steps.</em>',
      meta: "5-note scale · rotate ah / ee / oo",
      tip: "Each vowel sits in a different resonator. Feel the shift.",
    },
    swell: {
      eyebrow: "— messa di voce —",
      title: 'Soft to <em>loud</em>, back.',
      meta: "one note · grow and shrink, smoothly",
      tip: "Volume only. Same pitch. Breath does the work.",
    },
    stacc: {
      eyebrow: "— staccato —",
      title: 'Clean <em>onsets.</em>',
      meta: "1 · 3 · 5 · 8 · short, precise",
      tip: "Light, not hard. The cord touches — doesn't slam.",
    },
    cool: {
      eyebrow: "— cool-down —",
      title: 'Hum it <em>down.</em>',
      meta: "mid note · gentle, closed mouth",
      tip: "Easy. This settles the cords like a stretch after a run.",
    },
  },
  warmupDone: {
    eyebrowDone: "done",
    minSuffix: "min",
    titleA: "Voice is",
    titleB: "ready.",
    streakDay: "streak day",
    yourRange: "your range",
    steps: "steps",
    time: "time",
    oneThing: "one thing",
    thinking: "thinking…",
    llmFail: "(could not reach LLM)",
    saveFail: "could not save session",
    continuePrefix: "Continue",
    continueHint: "pick up where you left off",
    seeStats: "see stats",
    iAmDone: "i'm done",
    previewObservation: "Great session — your voice is warm and ready.",
  },
  progress: {
    eyebrow: "progress",
    titleA: "Your",
    titleB: "trail.",
    streak: "streak",
    days: "days",
    recentSessions: "recent sessions",
    noSessions: "no sessions yet — open warm-up to start",
    stepsSuffix: "steps",
    minSuffix: "min",
    peakPrefix: "peak",
  },
  profile: {
    eyebrow: "profile",
    titleA: "You",
    titleB: ".",
    voiceRange: "voice range",
    notSet: "not set yet",
    voiceFallback: "voice",
    redoRange: "redo range test",
    setupRange: "set up your range — 60s",
    aiLanguage: "ai response language",
    languageHint: "UI stays in English. End-of-session observations come back in this language.",
    streak: "streak",
    days: "days",
    logout: "log out",
  },
  login: {
    eyebrowLogin: "welcome back",
    eyebrowRegister: "make an account",
    titleLoginA: "Sign",
    titleLoginB: "in.",
    titleRegisterA: "Begin",
    titleRegisterB: "here.",
    subtitle: "email + password · no verification · no fuss",
    email: "email",
    password: "password",
    signIn: "▸ sign in",
    createAccount: "▸ create account",
    noAccount: "don't have an account?",
    haveAccount: "already have an account?",
    signUp: "sign up",
    switchToSignIn: "sign in",
  },
};

export type Dict = typeof en;
