import type { Dict } from "./en";

export const fr: Dict = {
  common: {
    back: "retour",
    continue: "continuer",
    loading: "…",
  },
  player: {
    mute: "muet",
    unmute: "son",
    solo: "solo",
  },
  range: {
    low: "grave",
    high: "aigu",
    now: "ici",
  },
  language: {
    eyebrow: "bienvenue",
    titleA: "Choisis ta",
    titleB: "langue.",
    subtitle: "L'interface reste en anglais. La réponse IA arrive dans cette langue.",
    continue: "continuer",
    options: ["English", "Russian", "Spanish", "German", "French", "Chinese"] as const,
  },
  library: {
    eyebrow: "Bibliothèque",
    titleA: "Tes",
    titleB: "chansons.",
    urlPlaceholder: "youtube.com/watch?v=...",
    paste: "COLLER",
    audioFile: "audio · vidéo",
    process: "traiter",
    queueing: "en file…",
    allChip: "tout",
    inProgressChip: "en cours",
    inProgressSection: "— en cours",
    readySection: "— prêt",
    empty: "La bibliothèque est vide.",
    bringSong: "ajoute une chanson",
    streakDay: "jour",
    streakDays: "jours",
    streakLabel: "série d'échauffements",
    warmFirst: "échauffe d'abord ta voix — 8 min",
    statusProcessing: "traitement",
    statusFailed: "échec",
    statusUntitled: "sans titre",
    delete: "supprimer",
  },
  karaoke: {
    eyebrow: "karaoké",
    titleA: "Avec voix",
    titleB: "ou sans.",
    loading: "chargement…",
    error: "erreur",
    clickToPlay: "touche pour lire",
    backToPlay: "sortir",
    showVideo: "vidéo",
    hideVideo: "sans vidéo",
    stems: "pistes",
    transport: "transport",
    tempo: "tempo · hauteur",
    music: "musique",
    splitMusic: "+ séparer la musique",
    hideSplit: "− masquer",
    nowStudying: "étude en cours",
    compactPlayer: "lecteur compact",
    toggleVideoTitle: "basculer le fond vidéo",
    hideControls: "masquer les contrôles",
    showControls: "afficher les contrôles",
    ariaSeek: "naviguer",
    ariaPlayPause: "lecture/pause",
    ariaBack15: "−15s",
    ariaForward15: "+15s",
    ariaMuteVocals: "couper la voix",
    ariaUnmuteVocals: "activer la voix",
    drillAB: "drill A–B",
  },
  play: {
    eyebrow: "en lecture",
    titleA: "Chante",
    titleB: "avec.",
    loading: "chargement des pistes…",
    stems: {
      vocals: "voix",
      instrum: "instrum.",
      drums: "batterie",
      bass: "basse",
      guitar: "guitare",
      piano: "piano",
      other: "autre",
    },
    showExtras: "+ batterie / basse",
    hideExtras: "− masquer",
    learnHint: "apprendre",
    karaokeHint: "karaoké",
    ariaPlayPause: "lecture/pause",
    ariaBack15: "−15s",
    ariaForward15: "+15s",
    ariaSeek: "naviguer",
  },
  processing: {
    eyebrow: "traitement",
    titleA: "Les pistes",
    titleB: "émergent.",
    titleFallback: "Sans titre",
    stageEyebrow: "étapes",
    leaveHint: "tu peux partir — on t'attend",
    errorPrefix: "erreur",
    stages: {
      resolve_input: "Téléchargement audio",
      separate: "Séparation des pistes",
      asr: "ASR · synchronisation des mots",
      lrclib: "Recherche LRCLib",
      align: "Alignement",
    },
    phases: {
      separate: [
        "séparation des canaux",
        "isolement de la voix",
        "extraction de la batterie",
        "remontée de la basse",
        "extraction guitare · piano",
        "finalisation",
      ],
    },
  },
  drill: {
    eyebrow: "drill",
    titleA: "Boucle",
    titleB: "ça.",
    emptyPhrase: "pas de phrase à drill — paroles non alignées",
    prevChunk: "fragment précédent",
    nextChunk: "fragment suivant",
    chunk: "fragment",
    line: "Ligne",
    custom: "Perso",
    pre: "pré",
    post: "post",
    tempo: "tempo",
    key: "tonalité",
    acappella: "a cappella",
    withVocals: "avec voix",
    minus: "minus",
    restartLoop: "boucle depuis A",
    loops: "boucles",
    mastered: "maîtrisé",
    gotIt: "compris",
    masteryNeedChunk: "enregistre d'abord le fragment",
    masteryUnmark: "retirer la maîtrise",
    masteryMark: "marquer maîtrisé & suivant",
    processing: "…",
  },
  select: {
    eyebrow: "choisis une phrase",
    titleA: "Quoi",
    titleB: "apprendre.",
    hint: "touche & glisse sur les mots pour choisir une phrase",
    word: "mot",
    words: "mots",
    clear: "effacer",
    drill: "drill",
    saveChunk: "enregistrer le fragment",
    myChunks: "mes fragments",
    stop: "stop",
    playAll: "tout lire",
    previewTitle: "aperçu",
    drillArrow: "drill →",
    loadStemsHint: "touche ▶ pour charger les pistes",
    mastered: "✓ maîtrisé",
    best: "meilleur",
    close: "fermer",
  },
  warmup: {
    eyebrow: "échauffement",
    titleA: "Réveille",
    titleB: "la voix.",
    rangeTuned: "réglé sur",
    rangeFirst: "d'abord, trouvons ton ambitus",
    todaysSession: "séance du jour",
    dailyTitle: "Daily 8",
    dailyMeta: "8 min · avant la pratique",
    streakNone: "prêt à commencer",
    streakDay: "jour",
    streakSuffix: "de série",
    startDaily: "commencer Daily 8",
    letsBegin: "commençons",
    setupRange: "Trouve ton ambitus — 60s",
    setupHint: "on adapte chaque exercice à ta voix",
    startOnboarding: "commencer l'intro",
    scienceNote: "5–8 minutes suffisent. L'échauffement compte plus que la méthode parfaite.",
    stepLabels: ["relâche", "lèvres", "sirène", "gamme", "swell", "stacc.", "détente"],
  },
  warmupOnboarding: {
    findingRange: "on cherche ton ambitus",
    scanA: "Glisse ta",
    scanB: "voix.",
    hintScan: "de ta note la plus grave confortable à la plus aigue\ntiens chaque extrémité une seconde, ça se verrouille",
    locked: "verrouillé",
    listening: "à l'écoute",
    detected: "détecté",
    tapMicToStart: "touche le micro pour démarrer",
    chestVoiceTip: "Chante en voix de poitrine — ton ton normal. Pas de fausset, pas de tension. Le confort gagne.",
    micDenied: "accès au micro refusé",
    startRecording: "démarrer l'enregistrement",
    stopRecording: "arrêter l'enregistrement",
    hintWhenRecording: "fais une pause quand tu as fini — ça s'enregistre tout seul",
    hintWhenIdle: "touche le micro, glisse du grave à l'aigu, puis pause",
  },
  warmupSession: {
    close: "fermer",
    of: "sur",
    prev: "préc.",
    next: "suiv.",
    pause: "pause",
    play: "lecture",
    skipHint: "— trop ? tape « suivant » pour passer",
    breathe: "respire · 4s inspire · 4s expire",
    breatheShort: "respire",
    holdOn: "tiens",
    steady: "stable",
    softLoudSoft: "doux → fort → doux",
    humSettle: "fredonne · laisse retomber",
    gentle: "doux",
    lip: "lèvre",
    trill: "trille",
    straw: "paille",
  },
  warmupSteps: {
    release: {
      eyebrow: "— relâcher le corps —",
      title: 'Ouvre la <em>mâchoire.</em>',
      meta: "bâillement-soupir · secoue-toi",
      tip: "Lâche la mâchoire, laisse sortir le soupir. Ne chante pas encore.",
    },
    sovt: {
      eyebrow: "— préparation SOVT —",
      title: 'Trilles de <em>lèvres</em> ou paille.',
      meta: 'choisis-en un · « brrr » doux ou chante dans une paille',
      tip: "Tractus semi-fermé = contre-pression. La façon la plus sûre de réveiller les cordes.",
    },
    siren: {
      eyebrow: "— sirènes —",
      title: 'Glisse du <em>grave</em> à l\'aigu.',
      meta: 'sur « ng » · grave → aigu → grave, fluide',
      tip: "Ne pousse pas en haut. Si ça force, baisse la cible — le confort gagne.",
    },
    scale: {
      eyebrow: "— gammes vocaliques —",
      title: 'Monte les <em>marches.</em>',
      meta: "gamme de 5 notes · alterne a / i / ou",
      tip: "Chaque voyelle vit dans un résonateur différent. Sens le changement.",
    },
    swell: {
      eyebrow: "— messa di voce —",
      title: 'Doux à <em>fort</em>, retour.',
      meta: "une note · enfle et décroît, doucement",
      tip: "Que le volume. Même hauteur. Le souffle fait le travail.",
    },
    stacc: {
      eyebrow: "— staccato —",
      title: 'Attaques <em>nettes.</em>',
      meta: "1 · 3 · 5 · 8 · court, précis",
      tip: "Léger, pas dur. La corde effleure — ne frappe pas.",
    },
    cool: {
      eyebrow: "— détente —",
      title: 'Fredonne <em>vers le bas.</em>',
      meta: "note moyenne · doux, bouche fermée",
      tip: "Tranquille. Ça calme les cordes comme un étirement après une course.",
    },
  },
  warmupDone: {
    eyebrowDone: "terminé",
    minSuffix: "min",
    titleA: "La voix",
    titleB: "est prête.",
    streakDay: "jour de série",
    yourRange: "ton ambitus",
    steps: "étapes",
    time: "temps",
    oneThing: "une chose",
    thinking: "réfléchit…",
    llmFail: "(LLM injoignable)",
    saveFail: "impossible d'enregistrer la séance",
    continuePrefix: "Continue",
    continueHint: "reprends où tu t'es arrêté",
    seeStats: "stats",
    iAmDone: "j'ai fini",
    previewObservation: "Belle séance — ta voix est chaude et prête.",
  },
  progress: {
    eyebrow: "progrès",
    titleA: "Ton",
    titleB: "parcours.",
    streak: "série",
    days: "jours",
    recentSessions: "séances récentes",
    noSessions: "aucune séance — ouvre l'échauffement pour commencer",
    stepsSuffix: "étapes",
    minSuffix: "min",
    peakPrefix: "pic",
  },
  profile: {
    eyebrow: "profil",
    titleA: "Toi",
    titleB: ".",
    voiceRange: "ambitus vocal",
    notSet: "pas encore défini",
    voiceFallback: "voix",
    redoRange: "refaire le test d'ambitus",
    setupRange: "définis ton ambitus — 60s",
    aiLanguage: "langue de réponse IA",
    languageHint: "L'interface reste en anglais. Les observations de fin de séance arrivent dans cette langue.",
    streak: "série",
    days: "jours",
    logout: "déconnexion",
  },
  login: {
    eyebrowLogin: "content de te revoir",
    eyebrowRegister: "crée un compte",
    titleLoginA: "Connecte",
    titleLoginB: "-toi.",
    titleRegisterA: "Commence",
    titleRegisterB: "ici.",
    subtitle: "email + mot de passe · sans vérification · sans tracas",
    email: "email",
    password: "mot de passe",
    signIn: "▸ connexion",
    createAccount: "▸ créer un compte",
    noAccount: "pas de compte ?",
    haveAccount: "déjà un compte ?",
    signUp: "s'inscrire",
    switchToSignIn: "connexion",
  },
};
