import type { Dict } from "./en";

export const zh: Dict = {
  common: {
    back: "返回",
    continue: "继续",
    loading: "…",
  },
  player: {
    mute: "静音",
    unmute: "取消静音",
    solo: "独奏",
  },
  range: {
    low: "低",
    high: "高",
    now: "当前",
  },
  language: {
    eyebrow: "欢迎",
    titleA: "选择你的",
    titleB: "语言。",
    subtitle: "界面保持英文。AI 反馈将以此语言呈现。",
    continue: "继续",
    options: ["English", "Russian", "Spanish", "German", "French", "Chinese"] as const,
  },
  library: {
    eyebrow: "曲库",
    titleA: "你的",
    titleB: "歌曲。",
    urlPlaceholder: "youtube.com/watch?v=...",
    paste: "粘贴",
    audioFile: "音频 · 视频",
    process: "处理",
    queueing: "排队中…",
    allChip: "全部",
    inProgressChip: "进行中",
    inProgressSection: "— 进行中",
    readySection: "— 就绪",
    empty: "曲库为空。",
    bringSong: "添加一首歌",
    streakDay: "天",
    streakDays: "天",
    streakLabel: "热身连续",
    warmFirst: "先热身 — 8 分钟",
    statusProcessing: "处理中",
    statusFailed: "失败",
    statusUntitled: "未命名",
    delete: "删除",
  },
  karaoke: {
    eyebrow: "卡拉OK",
    titleA: "带人声",
    titleB: "或不带。",
    loading: "加载中…",
    error: "错误",
    clickToPlay: "点击播放",
    backToPlay: "退出",
    showVideo: "视频",
    hideVideo: "无视频",
    stems: "音轨",
    transport: "传输",
    tempo: "速度 · 音调",
    music: "音乐",
    splitMusic: "+ 分离音乐",
    hideSplit: "− 隐藏分离",
    nowStudying: "正在学习",
    compactPlayer: "紧凑播放器",
    toggleVideoTitle: "切换视频背景",
    hideControls: "隐藏控件",
    showControls: "显示控件",
    ariaSeek: "跳转",
    ariaPlayPause: "播放/暂停",
    ariaBack15: "后退 15 秒",
    ariaForward15: "前进 15 秒",
    ariaMuteVocals: "静音人声",
    ariaUnmuteVocals: "取消人声静音",
    drillAB: "A–B 练习",
  },
  play: {
    eyebrow: "正在播放",
    titleA: "跟着",
    titleB: "唱。",
    loading: "加载音轨…",
    stems: {
      vocals: "人声",
      instrum: "伴奏",
      drums: "鼓",
      bass: "贝斯",
      guitar: "吉他",
      piano: "钢琴",
      other: "其他",
    },
    showExtras: "+ 鼓 / 贝斯",
    hideExtras: "− 隐藏额外",
    learnHint: "学习",
    karaokeHint: "卡拉OK",
    ariaPlayPause: "播放/暂停",
    ariaBack15: "后退 15 秒",
    ariaForward15: "前进 15 秒",
    ariaSeek: "跳转",
  },
  processing: {
    eyebrow: "处理中",
    titleA: "音轨正在",
    titleB: "生成。",
    titleFallback: "未命名",
    stageEyebrow: "阶段",
    leaveHint: "可以离开 — 回来时我们仍在这里",
    errorPrefix: "错误",
    stages: {
      resolve_input: "下载音频",
      separate: "音轨分离",
      asr: "ASR · 词级时间对齐",
      lrclib: "LRCLib 查找",
      align: "对齐",
    },
    phases: {
      separate: [
        "拆分声道",
        "分离人声",
        "提取鼓声",
        "提取贝斯",
        "提取吉他 · 钢琴",
        "收尾中",
      ],
    },
  },
  drill: {
    eyebrow: "练习",
    titleA: "循环",
    titleB: "练唱。",
    emptyPhrase: "没有可练习的乐句 — 该曲目没有对齐歌词",
    prevChunk: "上一段",
    nextChunk: "下一段",
    chunk: "片段",
    line: "行",
    custom: "自定义",
    pre: "前",
    post: "后",
    tempo: "速度",
    key: "调",
    acappella: "清唱",
    withVocals: "含人声",
    minus: "伴奏",
    restartLoop: "从 A 点重新循环",
    loops: "循环次数",
    mastered: "已掌握",
    gotIt: "明白了",
    masteryNeedChunk: "请先保存为片段以追踪掌握情况",
    masteryUnmark: "取消标记为已掌握",
    masteryMark: "标记为已掌握并继续",
    processing: "…",
  },
  select: {
    eyebrow: "选择乐句",
    titleA: "学习",
    titleB: "什么。",
    hint: "按住并拖动选择要练习的乐句",
    word: "词",
    words: "词",
    clear: "清除",
    drill: "练习",
    saveChunk: "保存片段",
    myChunks: "我的片段",
    stop: "停止",
    playAll: "全部播放",
    previewTitle: "预览",
    drillArrow: "练习 →",
    loadStemsHint: "点击 ▶ 加载音轨预览",
    mastered: "✓ 已掌握",
    best: "最佳",
    close: "关闭",
  },
  warmup: {
    eyebrow: "热身",
    titleA: "唤醒",
    titleB: "嗓音。",
    rangeTuned: "适配于",
    rangeFirst: "先找到你的音域",
    todaysSession: "今日训练",
    dailyTitle: "每日 8 分钟",
    dailyMeta: "8 分钟 · 练习前",
    streakNone: "准备开始",
    streakDay: "天",
    streakSuffix: "连续",
    startDaily: "开始每日 8 分钟",
    letsBegin: "开始吧",
    setupRange: "设置音域 — 60 秒",
    setupHint: "我们会根据你的嗓音调整每个练习",
    startOnboarding: "开始引导",
    scienceNote: "5–8 分钟就够了。热身这件事本身比完美的方法更重要。",
    stepLabels: ["release", "lip-trill", "siren", "scale", "swell", "staccato", "cool"],
  },
  warmupOnboarding: {
    findingRange: "正在寻找你的音域",
    scanA: "滑动你的",
    scanB: "嗓音。",
    hintScan: "从你最低的舒适音滑到最高的舒适音\n两端各保持一秒以锁定",
    locked: "已锁定",
    listening: "聆听中",
    detected: "已检测",
    tapMicToStart: "点击麦克风开始",
    chestVoiceTip: "用胸腔共鸣 — 你正常说话的音色。不用假声,不要勉强。舒适最重要。",
    micDenied: "麦克风访问被拒绝",
    startRecording: "开始录音",
    stopRecording: "停止录音",
    hintWhenRecording: "完成后稍作停顿 — 会自动保存",
    hintWhenIdle: "点击麦克风,从低到高滑动,然后停顿",
  },
  warmupSession: {
    close: "关闭",
    of: "/",
    prev: "上一步",
    next: "下一步",
    pause: "暂停",
    play: "播放",
    skipHint: "— 太多了?点击「下一步」跳过",
    breathe: "呼吸 · 吸 4 秒 · 呼 4 秒",
    breatheShort: "呼吸",
    holdOn: "保持",
    steady: "稳定",
    softLoudSoft: "轻 → 响 → 轻",
    humSettle: "哼鸣 · 让它沉淀",
    gentle: "轻柔",
    lip: "唇",
    trill: "颤音",
    straw: "吸管",
  },
  warmupSteps: {
    release: {
      eyebrow: "— 身体放松 —",
      title: '打开<em>下巴。</em>',
      meta: "打哈欠叹气 · 抖松身体",
      tip: "放下下巴,呼出叹息。先不要唱。",
    },
    sovt: {
      eyebrow: "— SOVT 入门 —",
      title: '唇颤<em>或</em>吸管。',
      meta: '选其一 · 轻柔"brrr"或通过吸管发声',
      tip: "半闭声道 = 反压。最安全的唤醒声带的方法。",
    },
    siren: {
      eyebrow: "— 警笛声 —",
      title: '从<em>低</em>滑到高。',
      meta: '用"ng"音 · 低 → 高 → 低,流畅',
      tip: "高音处不要用力。如果感到紧张,降低目标 — 舒适最重要。",
    },
    scale: {
      eyebrow: "— 元音音阶 —",
      title: '攀爬<em>音阶。</em>',
      meta: "5 音音阶 · 轮换 ah / ee / oo",
      tip: "每个元音落在不同的共鸣腔。感受这种切换。",
    },
    swell: {
      eyebrow: "— 渐强渐弱 —",
      title: '轻到<em>响</em>,再回来。',
      meta: "一个音 · 平滑地变大变小",
      tip: "只变音量。同一个音高。气息在工作。",
    },
    stacc: {
      eyebrow: "— 断音 —",
      title: '干净的<em>起音。</em>',
      meta: "1 · 3 · 5 · 8 · 短促,精准",
      tip: "轻巧,不重。声带触碰 — 不是撞击。",
    },
    cool: {
      eyebrow: "— 冷却 —",
      title: '哼鸣<em>下降。</em>',
      meta: "中音 · 轻柔,闭口",
      tip: "放轻松。这会让声带像跑步后的拉伸一样平静下来。",
    },
  },
  warmupDone: {
    eyebrowDone: "完成",
    minSuffix: "分钟",
    titleA: "嗓音已",
    titleB: "就绪。",
    streakDay: "连续天数",
    yourRange: "你的音域",
    steps: "步骤",
    time: "时间",
    oneThing: "一件事",
    thinking: "思考中…",
    llmFail: "(无法连接 LLM)",
    saveFail: "无法保存训练记录",
    continuePrefix: "继续",
    continueHint: "从你上次停下的地方接着来",
    seeStats: "查看统计",
    iAmDone: "我完成了",
    previewObservation: "训练很棒 — 你的嗓音已经热好,准备就绪。",
  },
  progress: {
    eyebrow: "进度",
    titleA: "你的",
    titleB: "足迹。",
    streak: "连续",
    days: "天",
    recentSessions: "最近训练",
    noSessions: "还没有训练 — 打开热身开始",
    stepsSuffix: "步骤",
    minSuffix: "分钟",
    peakPrefix: "峰值",
  },
  profile: {
    eyebrow: "个人资料",
    titleA: "关于",
    titleB: "你。",
    voiceRange: "音域",
    notSet: "尚未设置",
    voiceFallback: "嗓音",
    redoRange: "重新测试音域",
    setupRange: "设置音域 — 60 秒",
    aiLanguage: "AI 回复语言",
    languageHint: "界面保持英文。训练结束后的观察反馈将以此语言呈现。",
    streak: "连续",
    days: "天",
    logout: "退出登录",
  },
  login: {
    eyebrowLogin: "欢迎回来",
    eyebrowRegister: "创建账户",
    titleLoginA: "登",
    titleLoginB: "录。",
    titleRegisterA: "从这",
    titleRegisterB: "开始。",
    subtitle: "邮箱 + 密码 · 无需验证 · 简单直接",
    email: "邮箱",
    password: "密码",
    signIn: "▸ 登录",
    createAccount: "▸ 创建账户",
    noAccount: "还没有账户?",
    haveAccount: "已有账户?",
    signUp: "注册",
    switchToSignIn: "登录",
  },
};
