import type { Dict } from "./en";

export const de: Dict = {
  common: {
    back: "zurück",
    continue: "weiter",
    loading: "…",
  },
  player: {
    mute: "stumm",
    unmute: "Ton an",
    solo: "solo",
  },
  range: {
    low: "tief",
    high: "hoch",
    now: "jetzt",
  },
  language: {
    eyebrow: "willkommen",
    titleA: "Wähle deine",
    titleB: "Sprache.",
    subtitle: "Die Oberfläche bleibt auf Englisch. KI-Antworten kommen in dieser Sprache.",
    continue: "weiter",
    options: ["English", "Russian", "Spanish", "German", "French", "Chinese"] as const,
  },
  library: {
    eyebrow: "Bibliothek",
    titleA: "Deine",
    titleB: "Songs.",
    urlPlaceholder: "youtube.com/watch?v=...",
    paste: "EINFÜGEN",
    audioFile: "Audio · Video",
    process: "verarbeiten",
    queueing: "in Warteschlange…",
    allChip: "alle",
    inProgressChip: "läuft",
    inProgressSection: "— läuft",
    readySection: "— bereit",
    empty: "Die Bibliothek ist leer.",
    bringSong: "Song hinzufügen",
    streakDay: "Tag",
    streakDays: "Tage",
    streakLabel: "Aufwärm-Serie",
    warmFirst: "wärme zuerst deine Stimme auf — 8 Min",
    statusProcessing: "Verarbeitung",
    statusFailed: "Fehler",
    statusUntitled: "ohne Titel",
    delete: "löschen",
  },
  karaoke: {
    eyebrow: "Karaoke",
    titleA: "Mit Stimme",
    titleB: "oder ohne.",
    loading: "lädt…",
    error: "Fehler",
    clickToPlay: "tippen zum Abspielen",
    backToPlay: "verlassen",
    showVideo: "Video",
    hideVideo: "kein Video",
    stems: "Spuren",
    transport: "Steuerung",
    tempo: "Tempo · Tonhöhe",
    music: "Musik",
    splitMusic: "+ Musik aufteilen",
    hideSplit: "− verbergen",
    nowStudying: "übe gerade",
    compactPlayer: "kompakter Player",
    toggleVideoTitle: "Video-Hintergrund umschalten",
    hideControls: "Steuerung verbergen",
    showControls: "Steuerung anzeigen",
    ariaSeek: "spulen",
    ariaPlayPause: "Play/Pause",
    ariaBack15: "−15s",
    ariaForward15: "+15s",
    ariaMuteVocals: "Stimme stumm",
    ariaUnmuteVocals: "Stimme an",
    drillAB: "Drill A–B",
  },
  play: {
    eyebrow: "läuft jetzt",
    titleA: "Sing",
    titleB: "mit.",
    loading: "lade Spuren…",
    stems: {
      vocals: "Stimme",
      instrum: "instrum.",
      drums: "Schlagzeug",
      bass: "Bass",
      guitar: "Gitarre",
      piano: "Klavier",
      other: "andere",
    },
    showExtras: "+ Drums / Bass",
    hideExtras: "− verbergen",
    learnHint: "lernen",
    karaokeHint: "Karaoke",
    ariaPlayPause: "Play/Pause",
    ariaBack15: "−15s",
    ariaForward15: "+15s",
    ariaSeek: "spulen",
  },
  processing: {
    eyebrow: "Verarbeitung",
    titleA: "Spuren",
    titleB: "steigen auf.",
    titleFallback: "Ohne Titel",
    stageEyebrow: "Phasen",
    leaveHint: "du kannst gehen — wir warten",
    errorPrefix: "Fehler",
    stages: {
      resolve_input: "Audio wird geladen",
      separate: "Spurentrennung",
      asr: "ASR · Wort-Timing",
      lrclib: "LRCLib-Suche",
      align: "Alignment",
    },
    phases: {
      separate: [
        "Kanäle trennen",
        "Stimme isolieren",
        "Schlagzeug extrahieren",
        "Bass herausziehen",
        "Gitarre · Klavier holen",
        "Abschluss",
      ],
    },
  },
  drill: {
    eyebrow: "Drill",
    titleA: "Loope",
    titleB: "es.",
    emptyPhrase: "keine Phrase zum Üben — kein abgestimmter Text",
    prevChunk: "vorheriger Abschnitt",
    nextChunk: "nächster Abschnitt",
    chunk: "Abschnitt",
    line: "Zeile",
    custom: "Eigen",
    pre: "vor",
    post: "nach",
    tempo: "Tempo",
    key: "Tonart",
    acappella: "a cappella",
    withVocals: "mit Stimme",
    minus: "minus",
    restartLoop: "Loop von A neu",
    loops: "Loops",
    mastered: "gemeistert",
    gotIt: "kapiert",
    masteryNeedChunk: "speichere zuerst den Abschnitt",
    masteryUnmark: "Markierung entfernen",
    masteryMark: "als gemeistert markieren & weiter",
    processing: "…",
  },
  select: {
    eyebrow: "wähle eine Phrase",
    titleA: "Was",
    titleB: "lernen.",
    hint: "tippe & ziehe über Wörter, um eine Phrase zu wählen",
    word: "Wort",
    words: "Wörter",
    clear: "leeren",
    drill: "üben",
    saveChunk: "Abschnitt speichern",
    myChunks: "meine Abschnitte",
    stop: "stopp",
    playAll: "alles abspielen",
    previewTitle: "Vorschau",
    drillArrow: "üben →",
    loadStemsHint: "tippe ▶ um Spuren zu laden",
    mastered: "✓ gemeistert",
    best: "best",
    close: "schließen",
  },
  warmup: {
    eyebrow: "Aufwärmen",
    titleA: "Weck die",
    titleB: "Stimme.",
    rangeTuned: "abgestimmt auf",
    rangeFirst: "zuerst finden wir deinen Tonumfang",
    todaysSession: "heutige Sitzung",
    dailyTitle: "Daily 8",
    dailyMeta: "8 Min · vor dem Üben",
    streakNone: "bereit zu starten",
    streakDay: "Tag",
    streakSuffix: "Serie",
    startDaily: "Daily 8 starten",
    letsBegin: "fangen wir an",
    setupRange: "Tonumfang finden — 60s",
    setupHint: "wir passen jede Übung an deine Stimme an",
    startOnboarding: "Einrichtung starten",
    scienceNote: "5–8 Minuten reichen. Aufzuwärmen zählt mehr als die perfekte Methode.",
    stepLabels: ["lösen", "Lippen", "Sirene", "Skala", "Swell", "stacc.", "abkühlen"],
  },
  warmupOnboarding: {
    findingRange: "Tonumfang finden",
    scanA: "Lass deine",
    scanB: "Stimme gleiten.",
    hintScan: "vom tiefsten bequemen Ton bis zum höchsten\nhalte jedes Ende eine Sekunde, damit es einrastet",
    locked: "eingerastet",
    listening: "höre zu",
    detected: "erkannt",
    tapMicToStart: "tippe Mikro zum Starten",
    chestVoiceTip: "Sing in Bruststimme — dein normaler Sprechton. Kein Falsett, keine Anstrengung. Komfort gewinnt.",
    micDenied: "Mikro-Zugriff verweigert",
    startRecording: "Aufnahme starten",
    stopRecording: "Aufnahme stoppen",
    hintWhenRecording: "mach eine Pause wenn du fertig bist — es speichert sich",
    hintWhenIdle: "Mikro tippen, von tief nach hoch gleiten, dann Pause",
  },
  warmupSession: {
    close: "schließen",
    of: "von",
    prev: "zurück",
    next: "weiter",
    pause: "Pause",
    play: "Play",
    skipHint: "— zu viel? tippe „weiter“ zum Überspringen",
    breathe: "atme · 4s ein · 4s aus",
    breatheShort: "atme",
    holdOn: "halt",
    steady: "ruhig",
    softLoudSoft: "leise → laut → leise",
    humSettle: "summen · setzen lassen",
    gentle: "sanft",
    lip: "Lippe",
    trill: "Triller",
    straw: "Strohhalm",
  },
  warmupSteps: {
    release: {
      eyebrow: "— Körper lösen —",
      title: 'Öffne den <em>Kiefer.</em>',
      meta: "Gähn-Seufzer · schüttle dich locker",
      tip: "Kiefer fallen lassen, Seufzer rauslassen. Noch nicht singen.",
    },
    sovt: {
      eyebrow: "— SOVT-Vorbereitung —",
      title: 'Lippen-Triller <em>oder</em> Strohhalm.',
      meta: 'wähle eins · sanftes „brrr" oder durch einen Strohhalm singen',
      tip: "Halbgeschlossener Trakt = Gegendruck. Der sicherste Weg, die Stimmbänder zu wecken.",
    },
    siren: {
      eyebrow: "— Sirenen —",
      title: 'Gleite <em>tief</em> nach hoch.',
      meta: 'auf „ng" · tief → hoch → tief, sanft',
      tip: "Oben nicht drücken. Wenn es anstrengt, senke das Ziel — Komfort gewinnt.",
    },
    scale: {
      eyebrow: "— Vokal-Skalen —",
      title: 'Steige die <em>Stufen.</em>',
      meta: "5-Ton-Skala · wechsle a / i / u",
      tip: "Jeder Vokal sitzt in einem anderen Resonator. Spür die Verschiebung.",
    },
    swell: {
      eyebrow: "— messa di voce —",
      title: 'Leise zu <em>laut</em>, zurück.',
      meta: "eine Note · wachsen und schrumpfen, sanft",
      tip: "Nur Lautstärke. Gleiche Tonhöhe. Der Atem macht die Arbeit.",
    },
    stacc: {
      eyebrow: "— Staccato —",
      title: 'Saubere <em>Ansätze.</em>',
      meta: "1 · 3 · 5 · 8 · kurz, präzise",
      tip: "Leicht, nicht hart. Die Stimmbänder berühren — schlagen nicht.",
    },
    cool: {
      eyebrow: "— Abkühlen —",
      title: 'Summe <em>nach unten.</em>',
      meta: "mittlere Note · sanft, Mund geschlossen",
      tip: "Locker. Das beruhigt die Stimmbänder wie Dehnen nach dem Laufen.",
    },
  },
  warmupDone: {
    eyebrowDone: "fertig",
    minSuffix: "Min",
    titleA: "Die Stimme",
    titleB: "ist bereit.",
    streakDay: "Serien-Tag",
    yourRange: "dein Umfang",
    steps: "Schritte",
    time: "Zeit",
    oneThing: "eine Sache",
    thinking: "denke…",
    llmFail: "(LLM nicht erreichbar)",
    saveFail: "Sitzung konnte nicht gespeichert werden",
    continuePrefix: "Weiter mit",
    continueHint: "mach da weiter, wo du aufgehört hast",
    seeStats: "Statistik",
    iAmDone: "fertig",
    previewObservation: "Tolle Sitzung — deine Stimme ist warm und bereit.",
  },
  progress: {
    eyebrow: "Fortschritt",
    titleA: "Deine",
    titleB: "Spur.",
    streak: "Serie",
    days: "Tage",
    recentSessions: "letzte Sitzungen",
    noSessions: "noch keine Sitzungen — öffne Aufwärmen zum Starten",
    stepsSuffix: "Schritte",
    minSuffix: "Min",
    peakPrefix: "Peak",
  },
  profile: {
    eyebrow: "Profil",
    titleA: "Du",
    titleB: ".",
    voiceRange: "Stimmumfang",
    notSet: "noch nicht gesetzt",
    voiceFallback: "Stimme",
    redoRange: "Umfang neu messen",
    setupRange: "Umfang einrichten — 60s",
    aiLanguage: "KI-Antwortsprache",
    languageHint: "Oberfläche bleibt Englisch. Beobachtungen nach der Sitzung kommen in dieser Sprache.",
    streak: "Serie",
    days: "Tage",
    logout: "abmelden",
  },
  login: {
    eyebrowLogin: "willkommen zurück",
    eyebrowRegister: "Konto erstellen",
    titleLoginA: "Melde",
    titleLoginB: "dich an.",
    titleRegisterA: "Starte",
    titleRegisterB: "hier.",
    subtitle: "E-Mail + Passwort · keine Bestätigung · ohne Umstände",
    email: "E-Mail",
    password: "Passwort",
    signIn: "▸ anmelden",
    createAccount: "▸ Konto erstellen",
    noAccount: "kein Konto?",
    haveAccount: "schon ein Konto?",
    signUp: "registrieren",
    switchToSignIn: "anmelden",
  },
};
