export const en = {
  common: {
    back: "back",
    continue: "continue",
    loading: "…",
  },
  language: {
    eyebrow: "welcome",
    titleA: "Pick your",
    titleB: "language.",
    subtitle: "UI stays English. AI feedback comes in this language.",
    continue: "continue",
    options: ["English", "Russian", "Spanish", "German", "French", "Chinese"] as const,
  },
  library: {
    eyebrow: "Library",
    titleA: "Your",
    titleB: "songs.",
    urlPlaceholder: "youtube.com/watch?v=...",
    paste: "PASTE",
    audioFile: "audio · video",
    process: "process",
    queueing: "queueing…",
    allChip: "all",
    inProgressChip: "in progress",
    inProgressSection: "— in progress",
    readySection: "— ready",
    empty: "Library is empty.",
    bringSong: "bring a song",
    streakDay: "day",
    streakDays: "days",
    streakLabel: "warm-up streak",
    warmFirst: "warm up your voice first — 8 min",
    statusProcessing: "processing",
    statusFailed: "failed",
    statusUntitled: "untitled",
  },
  karaoke: {
    eyebrow: "karaoke",
    titleA: "With vocals",
    titleB: "or without.",
    loading: "loading…",
    error: "error",
    clickToPlay: "tap to play",
    backToPlay: "exit",
    showVideo: "video",
    hideVideo: "no video",
    stems: "stems",
    transport: "transport",
    tempo: "tempo · pitch",
    music: "music",
    splitMusic: "+ split music",
    hideSplit: "− hide split",
    nowStudying: "now studying",
    compactPlayer: "compact player",
    toggleVideoTitle: "toggle video background",
    hideControls: "hide controls",
    showControls: "show controls",
    ariaSeek: "seek",
    ariaPlayPause: "play/pause",
    ariaBack15: "back 15s",
    ariaForward15: "forward 15s",
    ariaMuteVocals: "mute vocals",
    ariaUnmuteVocals: "unmute vocals",
  },
  play: {
    eyebrow: "now playing",
    titleA: "Sing",
    titleB: "along.",
    loading: "loading stems…",
    stems: {
      vocals: "vocals",
      instrum: "instrum.",
      drums: "drums",
      bass: "bass",
      guitar: "guitar",
      piano: "piano",
      other: "other",
    },
    showExtras: "+ drums / bass",
    hideExtras: "− hide extras",
    learnHint: "learn",
  },
  processing: {
    eyebrow: "processing",
    titleA: "Stems are",
    titleB: "rising.",
    titleFallback: "Untitled",
    stageEyebrow: "stages",
    leaveHint: "feel free to leave — we'll be here when you're back",
    errorPrefix: "error",
    stages: {
      resolve_input: "Downloading audio",
      separate: "Stem separation",
      asr: "ASR · word-level timing",
      lrclib: "LRCLib lookup",
      align: "Alignment",
    },
    phases: {
      separate: [
        "splitting channels",
        "isolating vocals",
        "extracting drums",
        "lifting bass",
        "pulling guitar · piano",
        "finishing up",
      ],
    },
  },
  login: {
    eyebrowLogin: "welcome back",
    eyebrowRegister: "make an account",
    titleLoginA: "Sign",
    titleLoginB: "in.",
    titleRegisterA: "Begin",
    titleRegisterB: "here.",
    subtitle: "email + password · no verification · no fuss",
    email: "email",
    password: "password",
    signIn: "▸ sign in",
    createAccount: "▸ create account",
    noAccount: "don't have an account?",
    haveAccount: "already have an account?",
    signUp: "sign up",
    switchToSignIn: "sign in",
  },
} as const;

export type Dict = typeof en;
