import type { Dict } from "./en";

export const es: Dict = {
  common: {
    back: "atrás",
    continue: "continuar",
    loading: "…",
  },
  player: {
    mute: "silenciar",
    unmute: "activar",
    solo: "solo",
  },
  range: {
    low: "grave",
    high: "agudo",
    now: "ahora",
  },
  language: {
    eyebrow: "bienvenido",
    titleA: "Elige tu",
    titleB: "idioma.",
    subtitle: "La interfaz sigue en inglés. La respuesta de IA llega en este idioma.",
    continue: "continuar",
    options: ["English", "Russian", "Spanish", "German", "French", "Chinese"] as const,
  },
  library: {
    eyebrow: "Biblioteca",
    titleA: "Tus",
    titleB: "canciones.",
    urlPlaceholder: "youtube.com/watch?v=...",
    paste: "PEGAR",
    audioFile: "audio · vídeo",
    process: "procesar",
    queueing: "en cola…",
    allChip: "todo",
    inProgressChip: "en curso",
    inProgressSection: "— en curso",
    readySection: "— listo",
    empty: "La biblioteca está vacía.",
    bringSong: "añade una canción",
    streakDay: "día",
    streakDays: "días",
    streakLabel: "racha de calentamientos",
    warmFirst: "calienta tu voz primero — 8 min",
    statusProcessing: "procesando",
    statusFailed: "error",
    statusUntitled: "sin título",
    delete: "eliminar",
  },
  karaoke: {
    eyebrow: "karaoke",
    titleA: "Con voz",
    titleB: "o sin ella.",
    loading: "cargando…",
    error: "error",
    clickToPlay: "toca para reproducir",
    backToPlay: "salir",
    showVideo: "vídeo",
    hideVideo: "sin vídeo",
    stems: "pistas",
    transport: "transporte",
    tempo: "tempo · tono",
    music: "música",
    splitMusic: "+ separar música",
    hideSplit: "− ocultar",
    nowStudying: "estudiando ahora",
    compactPlayer: "reproductor compacto",
    toggleVideoTitle: "alternar fondo de vídeo",
    hideControls: "ocultar controles",
    showControls: "mostrar controles",
    ariaSeek: "buscar",
    ariaPlayPause: "play/pausa",
    ariaBack15: "−15s",
    ariaForward15: "+15s",
    ariaMuteVocals: "silenciar voz",
    ariaUnmuteVocals: "activar voz",
    drillAB: "ejercicio A–B",
  },
  play: {
    eyebrow: "reproduciendo",
    titleA: "Canta",
    titleB: "con ella.",
    loading: "cargando pistas…",
    stems: {
      vocals: "voz",
      instrum: "instrum.",
      drums: "batería",
      bass: "bajo",
      guitar: "guitarra",
      piano: "piano",
      other: "otro",
    },
    showExtras: "+ batería / bajo",
    hideExtras: "− ocultar",
    learnHint: "aprender",
    karaokeHint: "karaoke",
    ariaPlayPause: "play/pausa",
    ariaBack15: "−15s",
    ariaForward15: "+15s",
    ariaSeek: "buscar",
  },
  processing: {
    eyebrow: "procesando",
    titleA: "Las pistas",
    titleB: "surgen.",
    titleFallback: "Sin título",
    stageEyebrow: "etapas",
    leaveHint: "puedes salir — estaremos aquí cuando vuelvas",
    errorPrefix: "error",
    stages: {
      resolve_input: "Descargando audio",
      separate: "Separación de pistas",
      asr: "ASR · tiempos por palabra",
      lrclib: "Búsqueda en LRCLib",
      align: "Alineación",
    },
    phases: {
      separate: [
        "separando canales",
        "aislando la voz",
        "extrayendo batería",
        "subiendo el bajo",
        "sacando guitarra · piano",
        "terminando",
      ],
    },
  },
  drill: {
    eyebrow: "ejercicio",
    titleA: "Repítelo",
    titleB: "en bucle.",
    emptyPhrase: "no hay frase para ejercitar — no hay letra alineada",
    prevChunk: "fragmento anterior",
    nextChunk: "siguiente fragmento",
    chunk: "fragmento",
    line: "Línea",
    custom: "Personal",
    pre: "pre",
    post: "post",
    tempo: "tempo",
    key: "tono",
    acappella: "a capela",
    withVocals: "con voz",
    minus: "minus",
    restartLoop: "reiniciar bucle desde A",
    loops: "bucles",
    mastered: "dominado",
    gotIt: "entendido",
    masteryNeedChunk: "guarda primero el fragmento",
    masteryUnmark: "desmarcar dominado",
    masteryMark: "marcar dominado y seguir",
    processing: "…",
  },
  select: {
    eyebrow: "elige una frase",
    titleA: "Qué",
    titleB: "aprender.",
    hint: "toca y arrastra sobre las palabras para elegir la frase",
    word: "palabra",
    words: "palabras",
    clear: "limpiar",
    drill: "ejercitar",
    saveChunk: "guardar fragmento",
    myChunks: "mis fragmentos",
    stop: "parar",
    playAll: "reproducir todo",
    previewTitle: "vista previa",
    drillArrow: "ejercitar →",
    loadStemsHint: "toca ▶ para cargar las pistas",
    mastered: "✓ dominado",
    best: "mejor",
    close: "cerrar",
  },
  warmup: {
    eyebrow: "calentamiento",
    titleA: "Despierta",
    titleB: "la voz.",
    rangeTuned: "ajustado a",
    rangeFirst: "primero, encuentra tu rango",
    todaysSession: "sesión de hoy",
    dailyTitle: "Daily 8",
    dailyMeta: "8 min · antes de practicar",
    streakNone: "listo para empezar",
    streakDay: "día",
    streakSuffix: "de racha",
    startDaily: "iniciar Daily 8",
    letsBegin: "comencemos",
    setupRange: "Encuentra tu rango — 60s",
    setupHint: "ajustamos cada ejercicio a tu voz",
    startOnboarding: "iniciar configuración",
    scienceNote: "5–8 minutos bastan. El hecho de calentar importa más que el método perfecto.",
    stepLabels: ["liberar", "labio", "sirena", "escala", "swell", "stacc.", "calmar"],
  },
  warmupOnboarding: {
    findingRange: "encontrando tu rango",
    scanA: "Desliza tu",
    scanB: "voz.",
    hintScan: "desde tu nota más grave cómoda hasta la más aguda\nmantén cada extremo un segundo para fijarlo",
    locked: "fijado",
    listening: "escuchando",
    detected: "detectado",
    tapMicToStart: "toca el micrófono para empezar",
    chestVoiceTip: "Canta en voz de pecho — tu tono normal al hablar. Sin falsete, sin forzar. Lo cómodo gana.",
    micDenied: "acceso al micrófono denegado",
    startRecording: "empezar grabación",
    stopRecording: "detener grabación",
    hintWhenRecording: "haz una pausa cuando termines — se guardará solo",
    hintWhenIdle: "toca el micro, desliza de grave a agudo, luego pausa",
  },
  warmupSession: {
    close: "cerrar",
    of: "de",
    prev: "anterior",
    next: "siguiente",
    pause: "pausa",
    play: "play",
    skipHint: "— ¿demasiado? toca «siguiente» para saltar",
    breathe: "respira · 4s inhalas · 4s exhalas",
    breatheShort: "respira",
    holdOn: "mantén",
    steady: "firme",
    softLoudSoft: "suave → fuerte → suave",
    humSettle: "tararea · deja que se asiente",
    gentle: "suave",
    lip: "labio",
    trill: "trino",
    straw: "pajita",
  },
  warmupSteps: {
    release: {
      eyebrow: "— liberar el cuerpo —",
      title: 'Abre la <em>mandíbula.</em>',
      meta: "bostezo-suspiro · sacúdete",
      tip: "Suelta la mandíbula, deja salir el suspiro. Aún no cantes.",
    },
    sovt: {
      eyebrow: "— preparación SOVT —",
      title: 'Trinos de <em>labio</em> o pajita.',
      meta: 'elige uno · «brrr» suave o canta por una pajita',
      tip: "Tracto semicerrado = contrapresión. La forma más segura de despertar las cuerdas.",
    },
    siren: {
      eyebrow: "— sirenas —",
      title: 'Desliza <em>grave</em> a agudo.',
      meta: 'en «ng» · grave → agudo → grave, fluido',
      tip: "No fuerces arriba. Si tensa, baja el objetivo — gana la comodidad.",
    },
    scale: {
      eyebrow: "— escalas con vocales —",
      title: 'Sube los <em>peldaños.</em>',
      meta: "escala de 5 notas · alterna a / i / u",
      tip: "Cada vocal vive en un resonador distinto. Siente el cambio.",
    },
    swell: {
      eyebrow: "— messa di voce —",
      title: 'De suave a <em>fuerte</em>, vuelta.',
      meta: "una nota · crece y mengua, suavemente",
      tip: "Sólo volumen. Misma altura. El aliento hace el trabajo.",
    },
    stacc: {
      eyebrow: "— staccato —",
      title: 'Ataques <em>limpios.</em>',
      meta: "1 · 3 · 5 · 8 · corto y preciso",
      tip: "Ligero, no duro. La cuerda toca — no golpea.",
    },
    cool: {
      eyebrow: "— enfriamiento —",
      title: 'Tararea <em>hacia abajo.</em>',
      meta: "nota media · suave, boca cerrada",
      tip: "Tranquilo. Esto calma las cuerdas como un estiramiento tras correr.",
    },
  },
  warmupDone: {
    eyebrowDone: "hecho",
    minSuffix: "min",
    titleA: "Tu voz",
    titleB: "está lista.",
    streakDay: "día de racha",
    yourRange: "tu rango",
    steps: "pasos",
    time: "tiempo",
    oneThing: "una cosa",
    thinking: "pensando…",
    llmFail: "(no se pudo contactar al LLM)",
    saveFail: "no se pudo guardar la sesión",
    continuePrefix: "Continúa",
    continueHint: "retoma donde lo dejaste",
    seeStats: "ver estadísticas",
    iAmDone: "terminé",
    previewObservation: "Gran sesión — tu voz está caliente y lista.",
  },
  progress: {
    eyebrow: "progreso",
    titleA: "Tu",
    titleB: "camino.",
    streak: "racha",
    days: "días",
    recentSessions: "sesiones recientes",
    noSessions: "aún no hay sesiones — abre el calentamiento para empezar",
    stepsSuffix: "pasos",
    minSuffix: "min",
    peakPrefix: "pico",
  },
  profile: {
    eyebrow: "perfil",
    titleA: "Tú",
    titleB: ".",
    voiceRange: "rango vocal",
    notSet: "aún sin definir",
    voiceFallback: "voz",
    redoRange: "rehacer prueba de rango",
    setupRange: "configura tu rango — 60s",
    aiLanguage: "idioma de respuesta IA",
    languageHint: "La interfaz queda en inglés. Las observaciones tras la sesión llegan en este idioma.",
    streak: "racha",
    days: "días",
    logout: "cerrar sesión",
  },
  login: {
    eyebrowLogin: "bienvenido de nuevo",
    eyebrowRegister: "crea una cuenta",
    titleLoginA: "Inicia",
    titleLoginB: "sesión.",
    titleRegisterA: "Empieza",
    titleRegisterB: "aquí.",
    subtitle: "email + contraseña · sin verificación · sin lío",
    email: "email",
    password: "contraseña",
    signIn: "▸ iniciar sesión",
    createAccount: "▸ crear cuenta",
    noAccount: "¿no tienes cuenta?",
    haveAccount: "¿ya tienes cuenta?",
    signUp: "registrarse",
    switchToSignIn: "iniciar sesión",
  },
};
