import type { Dict } from "./en";

export const ru: Dict = {
  common: {
    back: "назад",
    continue: "продолжить",
    loading: "…",
  },
  player: {
    mute: "тишина",
    unmute: "звук",
    solo: "соло",
  },
  range: {
    low: "низ",
    high: "верх",
    now: "сейчас",
  },
  language: {
    eyebrow: "добро пожаловать",
    titleA: "Выбери",
    titleB: "язык.",
    subtitle: "Интерфейс остаётся на английском. AI-отклик придёт на этом языке.",
    continue: "продолжить",
    options: ["English", "Russian", "Spanish", "German", "French", "Chinese"] as const,
  },
  library: {
    eyebrow: "Библиотека",
    titleA: "Твои",
    titleB: "песни.",
    urlPlaceholder: "youtube.com/watch?v=...",
    paste: "ВСТАВИТЬ",
    audioFile: "аудио · видео",
    process: "обработать",
    queueing: "в очереди…",
    allChip: "все",
    inProgressChip: "в процессе",
    inProgressSection: "— в процессе",
    readySection: "— готово",
    empty: "Библиотека пуста.",
    bringSong: "добавить песню",
    streakDay: "день",
    streakDays: "дней",
    streakLabel: "серия разогревов",
    warmFirst: "сначала разогрей голос — 8 мин",
    statusProcessing: "обработка",
    statusFailed: "ошибка",
    statusUntitled: "без названия",
    delete: "удалить",
  },
  karaoke: {
    eyebrow: "караоке",
    titleA: "С вокалом",
    titleB: "или без.",
    loading: "загрузка…",
    error: "ошибка",
    clickToPlay: "коснись чтобы играть",
    backToPlay: "выход",
    showVideo: "видео",
    hideVideo: "без видео",
    stems: "дорожки",
    transport: "управление",
    tempo: "темп · тон",
    music: "музыка",
    splitMusic: "+ разбить музыку",
    hideSplit: "− свернуть",
    nowStudying: "сейчас учим",
    compactPlayer: "компактный плеер",
    toggleVideoTitle: "переключить фон",
    hideControls: "скрыть управление",
    showControls: "показать управление",
    ariaSeek: "перемотка",
    ariaPlayPause: "играть/пауза",
    ariaBack15: "−15с",
    ariaForward15: "+15с",
    ariaMuteVocals: "приглушить вокал",
    ariaUnmuteVocals: "включить вокал",
    drillAB: "разучивание A–B",
  },
  play: {
    eyebrow: "сейчас играет",
    titleA: "Пой",
    titleB: "вместе.",
    loading: "загрузка дорожек…",
    stems: {
      vocals: "вокал",
      instrum: "минус",
      drums: "ударные",
      bass: "бас",
      guitar: "гитара",
      piano: "пианино",
      other: "другое",
    },
    showExtras: "+ ударные / бас",
    hideExtras: "− скрыть",
    learnHint: "учить",
    karaokeHint: "караоке",
    ariaPlayPause: "играть/пауза",
    ariaBack15: "−15с",
    ariaForward15: "+15с",
    ariaSeek: "перемотка",
  },
  processing: {
    eyebrow: "обработка",
    titleA: "Дорожки",
    titleB: "поднимаются.",
    titleFallback: "Без названия",
    stageEyebrow: "этапы",
    leaveHint: "можешь выйти — мы подождём",
    errorPrefix: "ошибка",
    stages: {
      resolve_input: "Загрузка аудио",
      separate: "Разделение дорожек",
      asr: "ASR · слова с таймингом",
      lrclib: "Поиск в LRCLib",
      align: "Выравнивание",
    },
    phases: {
      separate: [
        "разделение каналов",
        "выделяем вокал",
        "вытаскиваем ударные",
        "поднимаем бас",
        "вытягиваем гитару · пианино",
        "финал",
      ],
    },
  },
  drill: {
    eyebrow: "разучивание",
    titleA: "Зацикли",
    titleB: "это.",
    emptyPhrase: "нет фразы для разучивания — нет выровненных слов",
    prevChunk: "предыдущий фрагмент",
    nextChunk: "следующий фрагмент",
    chunk: "фрагмент",
    line: "Строка",
    custom: "Свой",
    pre: "до",
    post: "после",
    tempo: "темп",
    key: "тон",
    acappella: "акапелла",
    withVocals: "с вокалом",
    minus: "минус",
    restartLoop: "повтор с точки A",
    loops: "повторы",
    mastered: "освоено",
    gotIt: "понял",
    masteryNeedChunk: "сначала сохрани фрагмент",
    masteryUnmark: "снять метку",
    masteryMark: "отметить и дальше",
    processing: "…",
  },
  select: {
    eyebrow: "выбери фразу",
    titleA: "Что",
    titleB: "учим.",
    hint: "проведи по словам — выбери фразу для разучивания",
    word: "слово",
    words: "слов",
    clear: "очистить",
    drill: "учить",
    saveChunk: "сохранить фрагмент",
    myChunks: "мои фрагменты",
    stop: "стоп",
    playAll: "играть всё",
    previewTitle: "превью",
    drillArrow: "учить →",
    loadStemsHint: "коснись ▶ чтобы загрузить дорожки",
    mastered: "✓ освоено",
    best: "лучший",
    close: "закрыть",
  },
  warmup: {
    eyebrow: "разогрев",
    titleA: "Разбуди",
    titleB: "голос.",
    rangeTuned: "настроен на",
    rangeFirst: "сначала найдём диапазон",
    todaysSession: "сегодняшняя сессия",
    dailyTitle: "Daily 8",
    dailyMeta: "8 мин · перед практикой",
    streakNone: "готов начать",
    streakDay: "день",
    streakSuffix: "подряд",
    startDaily: "начать Daily 8",
    letsBegin: "начнём",
    setupRange: "Найди диапазон — 60с",
    setupHint: "подгоним упражнения под твой голос",
    startOnboarding: "начать настройку",
    scienceNote: "5–8 минут хватит. Сам факт разогрева важнее идеального метода.",
    stepLabels: ["разрядка", "губы", "сирена", "гамма", "крещендо", "стаккато", "охлажд."],
  },
  warmupOnboarding: {
    findingRange: "находим диапазон",
    scanA: "Прокати",
    scanB: "голос.",
    hintScan: "от самой низкой комфортной ноты до самой высокой\nна каждом краю задержись на секунду — зафиксируется",
    locked: "зафиксировано",
    listening: "слушаю",
    detected: "поймал",
    tapMicToStart: "коснись микрофона чтобы начать",
    chestVoiceTip: "Пой грудным голосом — обычным разговорным тоном. Без фальцета, без напряжения. Комфорт важнее.",
    micDenied: "доступ к микрофону запрещён",
    startRecording: "начать запись",
    stopRecording: "остановить запись",
    hintWhenRecording: "замолкни на секунду когда закончишь — сохранится сам",
    hintWhenIdle: "коснись микрофона, проведи от низа до верха, замолкни",
  },
  warmupSession: {
    close: "закрыть",
    of: "из",
    prev: "назад",
    next: "далее",
    pause: "пауза",
    play: "играть",
    skipHint: "— слишком? нажми «далее» чтобы пропустить",
    breathe: "дыши · 4с вдох · 4с выдох",
    breatheShort: "дыши",
    holdOn: "держи",
    steady: "ровно",
    softLoudSoft: "тихо → громко → тихо",
    humSettle: "мычание · пусть осядет",
    gentle: "мягко",
    lip: "губы",
    trill: "трель",
    straw: "трубочка",
  },
  warmupSteps: {
    release: {
      eyebrow: "— разрядка тела —",
      title: 'Раскрой <em>челюсть.</em>',
      meta: "зевок-вздох · стряхни напряжение",
      tip: "Опусти челюсть, выпусти вздох. Петь пока не нужно.",
    },
    sovt: {
      eyebrow: "— SOVT-прайминг —",
      title: 'Губы <em>или</em> трубочка.',
      meta: 'выбери одно · мягкое «брр» или пение через трубочку',
      tip: "Полузакрытый тракт = противодавление. Самый безопасный способ разбудить связки.",
    },
    siren: {
      eyebrow: "— сирены —",
      title: 'Скользи <em>низ</em> к верху.',
      meta: 'на «нг» · низ → верх → низ, плавно',
      tip: "Не дави наверху. Если напрягает — понизь цель, комфорт важнее.",
    },
    scale: {
      eyebrow: "— гаммы на гласных —",
      title: 'Поднимись по <em>ступеням.</em>',
      meta: "5-нотная гамма · меняй а / и / у",
      tip: "Каждая гласная сидит в своём резонаторе. Чувствуй сдвиг.",
    },
    swell: {
      eyebrow: "— месса ди воче —",
      title: 'Тихо к <em>громко</em>, назад.',
      meta: "одна нота · растёт и стихает, плавно",
      tip: "Только громкость. Тон тот же. Работает дыхание.",
    },
    stacc: {
      eyebrow: "— стаккато —",
      title: 'Чистые <em>атаки.</em>',
      meta: "1 · 3 · 5 · 8 · коротко, точно",
      tip: "Легко, не жёстко. Связки касаются — не бьют.",
    },
    cool: {
      eyebrow: "— охлаждение —",
      title: 'Мычи <em>вниз.</em>',
      meta: "средняя нота · мягко, рот закрыт",
      tip: "Спокойно. Это успокаивает связки, как растяжка после бега.",
    },
  },
  warmupDone: {
    eyebrowDone: "готово",
    minSuffix: "мин",
    titleA: "Голос",
    titleB: "готов.",
    streakDay: "день серии",
    yourRange: "твой диапазон",
    steps: "шаги",
    time: "время",
    oneThing: "одно",
    thinking: "думаю…",
    llmFail: "(не удалось связаться с LLM)",
    saveFail: "не удалось сохранить сессию",
    continuePrefix: "Продолжить",
    continueHint: "вернись туда, где остановился",
    seeStats: "статистика",
    iAmDone: "я закончил",
    previewObservation: "Отличная сессия — голос разогрет и готов.",
  },
  progress: {
    eyebrow: "прогресс",
    titleA: "Твой",
    titleB: "путь.",
    streak: "серия",
    days: "дней",
    recentSessions: "недавние сессии",
    noSessions: "пока нет сессий — открой разогрев чтобы начать",
    stepsSuffix: "шагов",
    minSuffix: "мин",
    peakPrefix: "пик",
  },
  profile: {
    eyebrow: "профиль",
    titleA: "Ты",
    titleB: ".",
    voiceRange: "диапазон голоса",
    notSet: "ещё не задан",
    voiceFallback: "голос",
    redoRange: "переснять диапазон",
    setupRange: "найди свой диапазон — 60с",
    aiLanguage: "язык ответов AI",
    languageHint: "Интерфейс остаётся на английском. Наблюдения после сессии приходят на этом языке.",
    streak: "серия",
    days: "дней",
    logout: "выйти",
  },
  login: {
    eyebrowLogin: "с возвращением",
    eyebrowRegister: "создай аккаунт",
    titleLoginA: "Вход",
    titleLoginB: ".",
    titleRegisterA: "Начни",
    titleRegisterB: "здесь.",
    subtitle: "email + пароль · без подтверждения · просто",
    email: "email",
    password: "пароль",
    signIn: "▸ войти",
    createAccount: "▸ создать аккаунт",
    noAccount: "нет аккаунта?",
    haveAccount: "уже есть аккаунт?",
    signUp: "регистрация",
    switchToSignIn: "войти",
  },
};
